dialect = "us" 								
# search_mode = "fulltext"
# style = "compact"

sync_address = "http://192.168.1.54:8888"

# invert = true
workspaces = false
enter_accept = true

filter_mode = "host"
# filter_mode_shell_up_key_binding = "session" # or directory or host
inline_height = 10

## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
history_filter = [
   "^yt-dlp"
]

common_subcommands = [
  "cargo",
  "go",
  "git",
  "g",
  "npm",
  "yarn",
  "pnpm",
  "kubectl",
  "flub",
]
