dialect = "us" 								
# search_mode = "fulltext"
# style = "compact"

# sync_address = "http://192.168.1.4:8888"
sync_address = "https://atuin.btlr.org"

# invert = true
workspaces = false
enter_accept = true

filter_mode = "host"
# filter_mode_shell_up_key_binding = "session" # or directory or host
filter_mode_shell_up_key_binding = "directory" # or directory or host
inline_height = 10
store_failed = false
prefers_reduced_motion = true


## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
history_filter = [
   "^yt-dlp"
]

common_subcommands = [
  "apt",
  "cargo",
  "composer",
  "dnf",
  "docker",
  "git",
  "go",
  "ip",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",

  "g",
  "flub",
]

[sync]
records = true

[daemon]
enabled = true
