dialect = "us" 								
# search_mode = "fulltext"
# style = "compact"

# invert = true
workspaces = false

filter_mode = "host"
# filter_mode_shell_up_key_binding = "session" # or directory or host
inline_height = 10

## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
history_filter = [
   "^yt-dlp"
]
