location:
  source_directories:
    - "~"

  one_file_system: true
  repositories:
    - ska90w19@ska90w19.repo.borgbase.com:repo

  exclude_patterns:
    - '*.pyc'
    - ~/*/.cache

  exclude_caches: true
  exclude_if_present: .nobackup

storage:
  compression: auto,zstd
  # encryption_passphrase: CHANGEME
  ssh_command: 'ssh -i ~/.ssh/id_ed25519'
  archive_name_format: '{hostname}-{now}'

retention:
  keep_daily: 3
  keep_weekly: 4
  keep_monthly: 12
  keep_yearly: 2
  prefix: '{hostname}-'

consistency:
  checks:
    # uncomment to always do integrity checks. (takes long time for large repos)
    #- repository
    - disabled

  check_last: 3
  prefix: '{hostname}-'

hooks:
  # List of one or more shell commands or scripts to execute before creating a backup.
  before_backup:
    - echo "`date` - Starting backup"

  after_backup:
    - echo "`date` - Finished backup"
