[".local/zsh-autocomplete"]
    type = "archive"
    url = "https://github.com/marlonrichert/zsh-autocomplete/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "24h"

[".local/bin/ssh-ident"]
    type = "file"
    url = "https://github.com/ccontavalli/ssh-ident/raw/master/ssh-ident"
    executable = true
    refreshPeriod = "168h"

[".config/alacritty/default.yml"]
    type = "file"
    url = "https://github.com/alacritty/alacritty/raw/master/alacritty.yml"
    refreshPeriod = "168h" # 1 week

[".config/themes/alacritty/catppuccin.yml"]
    type = "file"
    url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin.yml"
    refreshPeriod = "168h" # 1 week

[".config/themes/alacritty/melange_dark.yml"]
    type = "file"
    url = "https://github.com/savq/melange/raw/master/term/alacritty/melange_dark.yml"
    refreshPeriod = "168h" # 1 week

[".config/themes/alacritty/melange_light.yml"]
    type = "file"
    url = "https://github.com/savq/melange/raw/master/term/alacritty/melange_light.yml"
    refreshPeriod = "168h" # 1 week

[".config/themes/alacritty/rigel.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/Rigellute/rigel/master/alacritty.yml"
    refreshPeriod = "168h" # 1 week

[".config/themes/alacritty/rose-pine.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/rose-pine/alacritty/main/dist/rose-pine.yml"
    refreshPeriod = "168h" # 1 week

[".config/themes/alacritty/rose-pine-dawn.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/rose-pine/alacritty/main/dist/rose-pine-dawn.yml"
    refreshPeriod = "168h" # 1 week

[".config/themes/alacritty/rose-pine-moon.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/rose-pine/alacritty/main/dist/rose-pine-moon.yml"
    refreshPeriod = "168h" # 1 week

[".config/themes/alacritty/selenized-black.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/jan-warchol/selenized/master/terminals/alacritty/selenized-black.yml"

[".config/themes/alacritty/selenized-dark.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/jan-warchol/selenized/master/terminals/alacritty/selenized-dark.yml"

[".config/themes/alacritty/selenized-light.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/jan-warchol/selenized/master/terminals/alacritty/selenized-light.yml"

[".config/themes/alacritty/selenized-white.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/jan-warchol/selenized/master/terminals/alacritty/selenized-white.yml"

[".config/oh-my-posh/hanselman.omp.json"]
    type = "file"
    url = "https://gist.githubusercontent.com/shanselman/1f69b28bfcc4f7716e49eb5bb34d7b2c/raw/8e9c9a8736ff4e9e5a863c20833d614549ccbc32/ohmyposhv3-v2.json"
    refreshPeriod = "48h"

[".config/themes/alacritty/spaceduck.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/pineapplegiant/spaceduck-terminal/main/spaceduck.yml"
    refreshPeriod = "168h" # 1 week
[".config/themes/zsh/headline.zsh-theme"]
    type = "file"
    url = "https://raw.githubusercontent.com/moarram/headline/main/headline.zsh-theme"
    refreshPeriod = "168h" # 1 week
[".config/themes/zsh/purify.zsh-theme"]
    type = "file"
    url = "https://raw.githubusercontent.com/kyoz/purify/master/zsh/purify.zsh-theme"
    refreshPeriod = "168h" # 1 week

[".local/antigen.zsh"]
    type = "file"
    url = "https://git.io/antigen"
    refreshPeriod = "168h"
[".local/bin/shell_colors"]
    type = "file"
    executable = true
    url = "https://gist.githubusercontent.com/rene-d/b5370efb61db005d7de0ad47959cd46c/raw/b32aa98a602b5f53d5c1977f2cb1a4cf87e28e90/shell_colors"
    refreshPeriod = "168h"
[".local/share/navi/cheats/navi.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/navi/raw/master/docs/navi.cheat"
[".local/share/navi/cheats/brew.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/master/pkg_mgr/apt.cheat"
[".local/share/navi/cheats/apt.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/master/pkg_mgr/brew.cheat"
[".local/share/navi/cheats/javascript.cheat"]
    type = "file"
    url = "https://github.com/denisidoro/cheats/raw/master/pkg_mgr/javascript.cheat"
