tap "oven-sh/bun"
brew "atuin", restart_service: :changed
brew "bat"
brew "bat-extras"
brew "biome"
brew "bottom"
brew "coreutils"
brew "difftastic"
brew "docker-credential-helper" if OS.mac?
brew "dust"
brew "eza"
brew "fd"
brew "gcc"
brew "fzf"
brew "gh"
brew "ghq"
brew "git-delta"
brew "git-lfs"
brew "gitui"
brew "go"
brew "hub"
brew "hugo"
brew "jj"
brew "jq"
brew "micro"
brew "mise"
brew "mosh"
brew "procs"
brew "ripgrep"
brew "sd"
brew "superfile"
brew "tealdeer"
brew "topgrade"
brew "tre-command"
brew "zellij"
brew "zoxide"
brew "oven-sh/bun/bun"

cask "ghostty" if OS.mac?
cask "git-credential-manager" if OS.mac?
cask "scroll-reverser" if OS.mac?
