"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Tyler Butler"
email = "tyler@tylerbutler.com"

[ui]
default-command = ["log"]
diff-editor = ":builtin"
editor = "micro"
pager = "delta"
# pager = "difft"

[ui.diff]
format = "git"

[fix.tools.biome-format]
command = ["biome", "format", "$path", "--write"]
patterns = ["glob:'**/*.*'"]

[git]
fetch = "origin"
push = "origin"
# fetch = ["origin", "upstream"]
