---
version: 1.0.0
default_namespace: default
config_home_path: /home/tylerbu/.config/hoard
trove_home_path: /home/tylerbu/.config/hoard/trove.yml
query_prefix: "  >"
primary_color:
  - 242
  - 229
  - 188
secondary_color:
  - 181
  - 118
  - 20
tertiary_color:
  - 50
  - 48
  - 47
command_color:
  - 180
  - 118
  - 20
parameter_token: "#"
