sources:
  - brew
  - apt
  - cargo
  # - npm
packages:
  - atuin
  - bat
  - bottom
  - direnv
  - difftastic
  - dust
  - eza
  - fd
  - fnm
  - fzf
  - github-cli
  - ghq
  - git-delta
  - gitui
  - hub
  - micro
  - nnn
  - ripgrep
  - sd
  - tealdeer
  - topgrade
  - zellij
  - zoxide

  # npm-only packages
  - "@fluidframework/build-tools@latest"
  - npm-check-updates
  - rimraf
  - tiged
  - vsts-npm-auth
  - yarn

  # cargo packages
  - blindspot
  - cargo-update
