sources:
  - brew
  - cargo
  # - npm
  - apt
packages:
  - bat
  - bottom
  - direnv
  - dust
  - eza
  - fd
  - fnm
  - fzf
  - gh
  - ghq
  - git-delta
  - gitui
  - hub
  - jq
  - mc
  - micro
  - nnn
  - rg
  - sd
  - tealdeer
  - thefuck
  - tmux
  - zellij
  - zoxide

  # npm-only packages
  - "@fluidframework/build-tools@latest"
  - npm-check-updates
  - rimraf
  - sort-package-json
  - tiged
  - vsts-npm-auth
  - yarn

  # cargo packages
  - blindspot
  - cargo-update
  - when-cli
